remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

title: The Vestigial Port Model (VPM)
tagline: A consciousness framework rooted in signal theory and simulation
description: A speculative theory linking the pineal gland to non-local consciousness fields, recursive simulation layers, and dimensional memory.
